# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: pillow
# in order of priority: highest (top) to lowest (bottom)
channels:
  - plotly
dependencies:
  - ipywidgets>=7.2
  - notebook>=5.3
  - plotly=4.5.2
  - matplotlib
  - pandas
  - xlrd >= 1.0.0
  - openpyxl
  - pillow
  - pip
  - scipy
  - pip:
      - scikit-image

